In [3]:
# R is a an open source programming language & software environment
# for statistical analysis, graphical representation,data analysis & visualization 
# R is a simple and easy to learn,read & write
# Developed by Ross Ihaka & Robert Gentleman at the University of 
# Auckland, Newzealand

# R is case sensitive 

In [4]:
5 + 6 # using R as a calculator
5 - 6
(5*6)/7

[1] 11

[1] -1

[1] 4.285714

In [5]:
1:50 # print numbers from 1:50
50:1 # print numbers 50:1 in reverse order
print(50:1)

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50

[1] 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
[26] 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1

 [1] 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
[26] 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1


In [7]:
print("Welcome to R Programming Session") # print anything  

print(25.5 + 12.7) # printing the calculation
25.5 + 12.7

[1] "Welcome to R Programming Session"
[1] 38.2


[1] 38.2

In [8]:
# help
help or ?
help("data.frame")
help("data.frame")
?read.csv

ERROR: Error in parse(text = x, srcfile = src): <text>:2:6: unexpected symbol
1: # help
2: help or
        ^


In [9]:
?read.csv

In [10]:
ctrl+l # to clear console window

ERROR: Error in eval(expr, envir, enclos): object 'ctrl' not found


In [11]:
# Data Types in R - Vector, List, Matrix, Array, Factor, Data Frame

# Vector - contains elements of same class
# there are 6 types of these atomic vectors, also known as 6 classes of vectors
# 1. Logical - True, False

In [12]:
a1 <- TRUE
a1

[1] TRUE

In [13]:
a <- c(TRUE, FALSE, TRUE, FALSE) # logical vector
a
class(a)

[1]  TRUE FALSE  TRUE FALSE

[1] "logical"

In [14]:
# 2. Numeric 
b <- c(0, 1, 2, 5.3, 4.22, 6, -2, 4, c(7, 8, 9)) # numeric vector
b
class(b)

[1]  0.00  1.00  2.00  5.30  4.22  6.00 -2.00  4.00  7.00  8.00  9.00

[1] "numeric"

In [15]:
# 3. Integer # Whole numbers & not a fraction
c <- c(2L, 34L, 0L)
c
class(c)

[1]  2 34  0

[1] "integer"

In [16]:
# 4. Complex
d <- 5 + 9i
d
class(d)

[1] 5+9i

[1] "complex"

In [17]:
# 5. Character
e <- c("Right now", 'it is', '10:15 am')
e
class(e)

[1] "Right now" "it is"     "10:15 am"

[1] "character"

In [18]:
# 6. Raw
f <- raw(100)
f
class(f)

  [1] 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 [26] 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 [51] 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 [76] 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

[1] "raw"

In [26]:
g <- charToRaw("john")
g
class(g)

[1] 6a 6f 68 6e

[1] "raw"

In [27]:
# accessing vector elements by their indeces or subscripts
a[1:3]
a[c(1,3)] 
# a[1:3] != a[c(1,3)]

[1]  TRUE FALSE  TRUE

[1] TRUE TRUE

In [28]:
# Viewing vectors in tabular format
View(a) # only helpful in small length vectors

ERROR: Error in View(a): 'View()' not yet supported in the Jupyter R kernel


In [30]:
# List -  can contain many different types of elements inside it like vectors, 
# functions and even another list inside it
h <- list(23, 21.3, c(2,5,3), "hello", sin)
h <- c(23, 21.3, c(2,5,3), "hello", sin)
h <- c(23, 21.3, c(2,5,3), "hello")
h <- c(23, 21.3, c(2,5,3), "hello", 3+5i, 2L)
h <- c(23, 21.3, c(2,5,3), "hello", 3+5i, 2L, mean)
class(h)
#View(h)
h <- list(23, 21.3, c(2,5,3), "hello", 3+5i, 2L)
h
#View(h)

[1] "list"

[[1]]
[1] 23

[[2]]
[1] 21.3

[[3]]
[1] 2 5 3

[[4]]
[1] "hello"

[[5]]
[1] 3+5i

[[6]]
[1] 2

In [33]:
#Accessing List elements by their index
h[[1]]
h[[3]][2]

[1] 23

[1] 5

In [34]:
h[[3]]

[1] 2 5 3

In [35]:
# Matrix - two-dimensional(rows*columns) rectangular data set 
# It can be created using a vector input to the matrix function
# The data elements must be of the same type
# All columns in a matrix must have the same type of mode(numeric, character, etc.) 
# and the same length
i <- matrix(c(10, 20, 30), nrow = 3, ncol = 2, byrow = TRUE, 
            dimnames = list(c('r1', 'r2', 'r3'), c('c1', 'c2')))
# default value for byrow is FALSE
class(i)
i

[1] "matrix"

c1 c2
r1 10 20
r2 30 10
r3 20 30

In [36]:
# Accessing elements of a matrix
i[3,2]

[1] 30

In [37]:
i[1]

[1] 10

In [38]:
i[1,2]

[1] 20

In [39]:
i[2,0]

numeric(0)

In [40]:
i[2,1]

[1] 30

In [42]:
# Array - While matrices are confined to 2 dimensions, arrays can be of any number of dimensions.

?array # help for array and details
j <- array(c("R", "Programming", "Session"), dim = c(2, 5, 4))
j

, , 1

     [,1]          [,2]      [,3]          [,4]          [,5]     
[1,] "R"           "Session" "Programming" "R"           "Session"
[2,] "Programming" "R"       "Session"     "Programming" "R"      

, , 2

     [,1]          [,2]          [,3]      [,4]          [,5]         
[1,] "Programming" "R"           "Session" "Programming" "R"          
[2,] "Session"     "Programming" "R"       "Session"     "Programming"

, , 3

     [,1]      [,2]          [,3]          [,4]      [,5]         
[1,] "Session" "Programming" "R"           "Session" "Programming"
[2,] "R"       "Session"     "Programming" "R"       "Session"    

, , 4

     [,1]          [,2]      [,3]          [,4]          [,5]     
[1,] "R"           "Session" "Programming" "R"           "Session"
[2,] "Programming" "R"       "Session"     "Programming" "R"

[1] "array"

In [43]:
class(j)

[1] "array"

In [44]:
# Accessing an array
j[,,4] # 4th array 
# Accessing individual element from an array
j[2,5,4] # 2nd row, 5th column, 4th array 

[,1]        [,2]    [,3]        [,4]        [,5]   
[1,] R           Session Programming R           Session
[2,] Programming R       Session     Programming R

[1] "R"

In [46]:
# Factor - variable which can take certain values(levels) and not any
k <- c("red", "green", "blue", "blue", "red", "red")
class(k)
factor_k <- factor(k)
class(factor_k)
factor_k

[1] "character"

[1] "factor"

[1] red   green blue  blue  red   red  
Levels: blue green red

In [47]:
factor_k

[1] red   green blue  blue  red   red  
Levels: blue green red

In [48]:
l <- c(1, 2, 3, 4, 4, 5, 3, 2, 5.1)
l
class(l)
factor_l <- factor(l)
class(factor_l)
factor_l

[1] 1.0 2.0 3.0 4.0 4.0 5.0 3.0 2.0 5.1

[1] "numeric"

[1] "factor"

[1] 1   2   3   4   4   5   3   2   5.1
Levels: 1 2 3 4 5 5.1

In [49]:
# Data Frame
# Unlike a matrix in data frame each column can contain different modes of data
# It is a list of vectors of equal length
m <- data.frame(gender = c("Male", "Male","Female"), height = c(152, 171.5, 165), 
                weight = c(81,93, 78), Age = c(42,38,26))
class(m)
m

[1] "data.frame"

gender height weight Age
1 Male   152.0  81     42 
2 Male   171.5  93     38 
3 Female 165.0  78     26

In [53]:
# Accessing columns/features of a data frame
m[1]

gender
1 Male  
2 Male  
3 Female

In [54]:
class(m[1])

[1] "data.frame"

In [55]:
# Accessing elements of a data frame
m$gender
class(m$gender)
m$gender[3]
class(m$gender[3])

[1] Male   Male   Female
Levels: Female Male

[1] "factor"

[1] Female
Levels: Female Male

[1] "factor"

In [56]:
m$gender


[1] Male   Male   Female
Levels: Female Male

In [57]:
m$gender[3]


[1] Female
Levels: Female Male

In [58]:
class(m$gender[3])

[1] "factor"

In [59]:
class(m$gender)

[1] "factor"

In [60]:
m[[2]]
class(m[[2]])
m[[2]][2]

[1] 152.0 171.5 165.0

[1] "numeric"

[1] 171.5

In [61]:
m[c(1,2), 2] # accessing multiple items from a data frame

[1] 152.0 171.5

#### End of Data Types

##### Variables or Objects in R

In [62]:
# valid & invalid variable types
# Valid
var_name2. <- 1 # Has letters, numbers, dot and underscore
.var_name <- 2 # Can start with a dot(.) but the dot(.)should not be followed by a number
var.name <- 3

In [63]:
# Invalid 
var_name% <- 4 # Only dot(.) and underscore allowed 
2var_name <- 5 # cannot start with a number
.2var_name <- 6 # dot followed by a number makes it invalid
_var_name <- 7 # cannot start with _

ERROR: Error in parse(text = x, srcfile = src): <text>:2:9: unexpected input
1: # Invalid 
2: var_name% <- 4 # Only dot(.) and underscore allowed 
           ^


In [64]:
# Variable Assignment
# The variables can be assigned values using leftward, rightward and equal to operator

In [65]:
# Assignment using leftward operator
var.1 <- c("R","Programming") 
# Assignment using rightward operator
c(TRUE,1) -> var.2   
# Assignment using equal operator
var.3 = c(0,1,2,3)

In [67]:
# Finding Variables in Environment
ls()

[1] "a"          "a1"         "b"          "c"          "d"         
 [6] "df"         "e"          "f"          "factor_k"   "factor_l"  
[11] "g"          "h"          "i"          "j"          "k"         
[16] "l"          "m"          "var.1"      "var.2"      "var.3"     
[21] "var.name"   "var_name2."

In [75]:
# ls(pattern = "var") # displays variable with var text in it

character(0)

In [69]:
ls(all.name = TRUE) # also displays hidden(starting with .) variables

[1] ".pbd_env"   ".var_name"  "a"          "a1"         "b"         
 [6] "c"          "d"          "df"         "e"          "f"         
[11] "factor_k"   "factor_l"   "g"          "h"          "i"         
[16] "j"          "k"          "l"          "m"          "var.1"     
[21] "var.2"      "var.3"      "var.name"   "var_name2."

In [73]:
# Deleting variables 
var1 <- 1
ls(pattern = "var")


[1] "var1"

In [74]:
rm(list = ls(pattern = "var")) # will remove all variables with var text in it

##### End of Variables

#### Operators in R


In [76]:
# 5 = Arithmetic, Relational, Logical, Assignment, Miscellaneous 

# Arithmetic Operators
n <- c(1, 2.4, 5)
o <- c(3, 4.7, 9.1)
p <- c(1.9, 2, 7)
# 1. + addition
n+o+p

[1]  5.9  9.1 21.1

In [77]:
# 2. - subtraction
n-o
n-o-p

[1] -2.0 -2.3 -4.1

[1]  -3.9  -4.3 -11.1

In [78]:
# 3. * multiplication
n*o*p

# 4. / division
n/o/p

[1]   5.70  22.56 318.50

[1] 0.17543860 0.25531915 0.07849294

In [79]:
# 5. %% Give the remainder of the first vector with the second
n%%o 

# 6. %/% The result of division of first vector with second (quotient)
n%/%o 

# 7. ^ The first vector raised to the exponent of second vector	
p^o

[1] 1.0 2.4 5.0

[1] 0 0 0

[1] 6.859000e+00 2.599208e+01 4.902213e+07

In [80]:
# Relational Operators - returns boolean values
q <- c(1, 3, 4, 3, 2)
r <- c(2, 4, 4, 5, 2)

In [81]:
# 1. > greater than 
q[1] > r[2]

# 2. < lesser than
q < r

# 3. == equal to
q == r

# 4. >= greater than or equal to
q >= r

# 5. <= lesser than or equal to 
q <= r

# 6. != not equal to 
q != r

[1] FALSE

[1]  TRUE  TRUE FALSE  TRUE FALSE

[1] FALSE FALSE  TRUE FALSE  TRUE

[1] FALSE FALSE  TRUE FALSE  TRUE

[1] TRUE TRUE TRUE TRUE TRUE

[1]  TRUE  TRUE FALSE  TRUE FALSE

In [82]:
# Relational Operators
# Condition: All numbers greater than 1 are considered as logical value TRUE
s <- c(3, 1, TRUE, 2+2i) 
t <- c(4, 1, FALSE, 2+3i)

In [83]:
# 1. & Element-wise Logical AND 
s&t
# 2. | Element-wise Logical OR 
s|t
# 3. ! Logical NOT - can be appied on a single vector
!(s&t)
!(s|t)

[1]  TRUE  TRUE FALSE  TRUE

[1] TRUE TRUE TRUE TRUE

[1] FALSE FALSE  TRUE FALSE

[1] FALSE FALSE FALSE FALSE

In [84]:
# Logical Operators (&& || considers only 1st element of the vectors and give a vector of 
# single element as output)
# 4. && Logical AND
u <- c(3, 0, TRUE, 2+2i)
v <- c(1, 3, TRUE, 2+3i)
u&&v

[1] TRUE

In [85]:
# 5. || Logical OR
x <- c(0,0,TRUE,2+2i)
y <- c(0,3,TRUE,2+3i)
x||y

[1] FALSE

In [86]:
# Assignment Operators
# 1. Left Assignment <- or == or <<-
v1 <- c(3,1,TRUE,2+3i)
v2 <<- c(3,1,TRUE,2+3i)
v3 = c(3,1,TRUE,2+3i)

In [87]:
v1

[1] 3+0i 1+0i 1+0i 2+3i

In [88]:
v2

[1] 3+0i 1+0i 1+0i 2+3i

In [89]:
v3

[1] 3+0i 1+0i 1+0i 2+3i

In [90]:
# 2. Right Assignment -> or ->>
c(3,1,TRUE,2+3i) -> v4
c(3,1,TRUE,2+3i) ->> v5
v4
v5

[1] 3+0i 1+0i 1+0i 2+3i

[1] 3+0i 1+0i 1+0i 2+3i

In [91]:
# Miscellaneous Operators
# 1. : Colon Operator - It creates the series of numbers in sequence for a vector
v6 <- 1.5:10.5
v6

[1]  1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5

In [92]:
# 2. %in% - an element belongs to a vector
v7 <- c(8, 9, 10)
v8 <- c(12, 13, 14)
t <- 1:10
v7 %in% t
v8 %in% t

[1] TRUE TRUE TRUE

[1] FALSE FALSE FALSE

In [93]:
# 3. %*% - multiply a matrix with its transpose
v9 <- matrix( c(2, 6, 5, 1, 10, 4), nrow = 2, ncol = 3, byrow = TRUE)
v9
t(v9)
v9t <- v9 %*% t(v9)
v9t

[,1] [,2] [,3]
[1,] 2     6   5   
[2,] 1    10   4

[,1] [,2]
[1,] 2     1  
[2,] 6    10  
[3,] 5     4

[,1] [,2]
[1,] 65    82 
[2,] 82   117