In [1]:
# Common Functions used in R

# Strings
# Paste - combine character strings in R

In [2]:
# simple paste function 
paste('one',2,'three',4,'five') # default sep is space ' '

[1] "one 2 three 4 five"

In [3]:
# paste function with sep argument
paste('X', 1:5,sep = '') # sep = to separate the terms

[1] "X1" "X2" "X3" "X4" "X5"

In [4]:
# paste function with collapse Argument
paste(c('one','two','three','four'), collapse = ' and ') # collapse =  to separate the results

[1] "one and two and three and four"

In [5]:
# paste function in R with separator and collapse Argument
paste(c('X','Y'), 1:5, sep = '_', collapse = ' and ')

[1] "X_1 and Y_2 and X_3 and Y_4 and X_5"

In [6]:
# paste(0)
paste0('one',2,'three',4,'five')

[1] "one2three4five"

In [7]:
# Sort - sort numerical values or character strings
# numerical vector sort
v1 <- c(1,2,4,5,7,11)

In [8]:
sort(v1) # increasing is default

[1]  1  2  4  5  7 11

In [9]:
sort(v1, decreasing=TRUE) # sorts in descending order

[1] 11  7  5  4  2  1

In [10]:
# Character vector sort
v2 <- c("Cherry","BlueBerry","Apple","Pineapple")

In [11]:
sort(v2) # sorts in Alphabetical order which is default

[1] "Apple"     "BlueBerry" "Cherry"    "Pineapple"

In [12]:
sort(v2,decreasing = TRUE) # sorts in Reverse Alphabetical order

[1] "Pineapple" "Cherry"    "BlueBerry" "Apple"

In [13]:
# unlist
mylist = list(c(1,4,6),"dog",3,"cat",TRUE,c(9,10,11))
mylist

[[1]]
[1] 1 4 6

[[2]]
[1] "dog"

[[3]]
[1] 3

[[4]]
[1] "cat"

[[5]]
[1] TRUE

[[6]]
[1]  9 10 11

In [14]:
class(mylist)

[1] "list"

In [15]:
unlist(mylist)

[1] "1"    "4"    "6"    "dog"  "3"    "cat"  "TRUE" "9"    "10"   "11"

In [16]:
class(unlist(mylist))

[1] "character"

In [17]:
# Merge Lists
list1 <- list(1,2,3)
list2 <- list("Jan","Feb","Mar")

In [18]:
merged.list <- c(list1,list2)
merged.list

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] "Jan"

[[5]]
[1] "Feb"

[[6]]
[1] "Mar"

In [19]:
# Matrix Computations
matrix1 <- matrix(c(1, 3, 5, 7), nrow = 2)
matrix2 <- matrix(c(2, 4, 6, 8), nrow = 2)
matrix1
matrix2

[,1] [,2]
[1,] 1    5   
[2,] 3    7

[,1] [,2]
[1,] 2    6   
[2,] 4    8

In [20]:
# Add the matrices.
Mat.Add <- matrix1 + matrix2
Mat.Add

[,1] [,2]
[1,] 3    11  
[2,] 7    15

In [21]:
# Subtract the matrices
Mat.Sub <- matrix1 - matrix2
Mat.Sub

[,1] [,2]
[1,] -1   -1  
[2,] -1   -1

In [24]:
# Multiply the matrices.
Mat.Multi <- matrix1 * matrix2
Mat.Multi

[,1] [,2]
[1,]  2   30  
[2,] 12   56

In [25]:
# Divide the matrices
Mat.Div <- matrix1 / matrix2
Mat.Div

[,1] [,2]     
[1,] 0.50 0.8333333
[2,] 0.75 0.8750000

In [26]:
week = c("sunday","monday","tuesday","wednesday","thursday","friday","saturday","wednesday","tuesday","thursday","wednesday")
week

[1] "sunday"    "monday"    "tuesday"   "wednesday" "thursday"  "friday"   
 [7] "saturday"  "wednesday" "tuesday"   "thursday"  "wednesday"

In [27]:
table(week)

week
   friday    monday  saturday    sunday  thursday   tuesday wednesday 
        1         1         1         1         2         2         3 

In [28]:
prop.table(table(week))*100

week
   friday    monday  saturday    sunday  thursday   tuesday wednesday 
 9.090909  9.090909  9.090909  9.090909 18.181818 18.181818 27.272727 

In [29]:
week_ordered = factor(week, levels=c("sunday","monday","tuesday","wednesday","thursday","friday","saturday"), ordered=TRUE)
week_ordered

[1] sunday    monday    tuesday   wednesday thursday  friday    saturday 
 [8] wednesday tuesday   thursday  wednesday
7 Levels: sunday < monday < tuesday < wednesday < thursday < ... < saturday

In [30]:
table(week_ordered)

week_ordered
   sunday    monday   tuesday wednesday  thursday    friday  saturday 
        1         1         2         3         2         1         1 

In [31]:
prop.table(table(week_ordered))

week_ordered
    sunday     monday    tuesday  wednesday   thursday     friday   saturday 
0.09090909 0.09090909 0.18181818 0.27272727 0.18181818 0.09090909 0.09090909 

In [32]:
sort(prop.table(table(week_ordered))) # increasing order by default

week_ordered
    sunday     monday     friday   saturday    tuesday   thursday  wednesday 
0.09090909 0.09090909 0.09090909 0.09090909 0.18181818 0.18181818 0.27272727 

In [33]:
sort(prop.table(table(week_ordered)), decreasing = TRUE) # decreasing order

week_ordered
 wednesday    tuesday   thursday     sunday     monday     friday   saturday 
0.27272727 0.18181818 0.18181818 0.09090909 0.09090909 0.09090909 0.09090909 

In [35]:

# Create the data frame.
emp.data <- data.frame(emp_id = c (1:5),
                       emp_name = c("john","marsh","mitchell","lara","peter"),
                       salary = c(6213,1515,4113,3729,2843),
                       joining_date = as.Date(c("2012-12-01","2014-07-23","2012-11-15","2015-05-11","2016-03-27")),
                       stringsAsFactors=FALSE )

In [36]:
emp.data

emp_id emp_name salary joining_date
1 1      john     6213   2012-12-01  
2 2      marsh    1515   2014-07-23  
3 3      mitchell 4113   2012-11-15  
4 4      lara     3729   2015-05-11  
5 5      peter    2843   2016-03-27

In [37]:
emp.data[1:2, ] # accessing 1st 2 cols & all rows

emp_id emp_name salary joining_date
1 1      john     6213   2012-12-01  
2 2      marsh    1515   2014-07-23

In [38]:
emp.data[ ,1:3] # accessing all rows & 1st 3 cols

emp_id emp_name salary
1 1      john     6213  
2 2      marsh    1515  
3 3      mitchell 4113  
4 4      lara     3729  
5 5      peter    2843

In [39]:
emp.data[c(3,5),c(2,4)] # accessing 3,5 rows and 2,4 cols

emp_name joining_date
3 mitchell 2012-11-15  
5 peter    2016-03-27

In [40]:
# cbind 
# adding col without cbind
emp.data$dept <- c("IT","Operations","IT","HR","Finance") # adding the "dept" column
emp.data

emp_id emp_name salary joining_date dept      
1 1      john     6213   2012-12-01   IT        
2 2      marsh    1515   2014-07-23   Operations
3 3      mitchell 4113   2012-11-15   IT        
4 4      lara     3729   2015-05-11   HR        
5 5      peter    2843   2016-03-27   Finance

In [41]:
# adding col using cbind
designation <- c ("Entry level","Manager","Technical specialist","Entry level","Senior Level")
emp.table<-cbind(emp.data,designation)
emp.table

emp_id emp_name salary joining_date dept       designation         
1 1      john     6213   2012-12-01   IT         Entry level         
2 2      marsh    1515   2014-07-23   Operations Manager             
3 3      mitchell 4113   2012-11-15   IT         Technical specialist
4 4      lara     3729   2015-05-11   HR         Entry level         
5 5      peter    2843   2016-03-27   Finance    Senior Level

In [42]:
emp1 <- cbind(designation, emp.data)
emp1

designation          emp_id emp_name salary joining_date dept      
1 Entry level          1      john     6213   2012-12-01   IT        
2 Manager              2      marsh    1515   2014-07-23   Operations
3 Technical specialist 3      mitchell 4113   2012-11-15   IT        
4 Entry level          4      lara     3729   2015-05-11   HR        
5 Senior Level         5      peter    2843   2016-03-27   Finance

In [43]:
names(emp1)

[1] "designation"  "emp_id"       "emp_name"     "salary"       "joining_date"
[6] "dept"

In [44]:
emp1 = emp1[,c(2,3,1,4:6)]
emp1

emp_id emp_name designation          salary joining_date dept      
1 1      john     Entry level          6213   2012-12-01   IT        
2 2      marsh    Manager              1515   2014-07-23   Operations
3 3      mitchell Technical specialist 4113   2012-11-15   IT        
4 4      lara     Entry level          3729   2015-05-11   HR        
5 5      peter    Senior Level         2843   2016-03-27   Finance

In [45]:
# rbind
# Create the second data frame. 
emp.table.new <- data.frame(
  emp_id = c (6:8),
  emp_name = c("lila","raj","tera"),
  salary = c(2413,5415,6413),
  joining_date = as.Date(c("2014-03-01","2015-07-23","2016-11-15")),
  dept=c("IT","Finance","Operartions"),
  designation = c("Manager","Entry level","Senior Level"),
  stringsAsFactors=FALSE
)

In [46]:
emp.table.new

emp_id emp_name salary joining_date dept        designation 
1 6      lila     2413   2014-03-01   IT          Manager     
2 7      raj      5415   2015-07-23   Finance     Entry level 
3 8      tera     6413   2016-11-15   Operartions Senior Level

In [47]:
# Binds the two data frames
emp.table.final<- rbind(emp.table,emp.table.new)
emp.table.final

emp_id emp_name salary joining_date dept        designation         
1 1      john     6213   2012-12-01   IT          Entry level         
2 2      marsh    1515   2014-07-23   Operations  Manager             
3 3      mitchell 4113   2012-11-15   IT          Technical specialist
4 4      lara     3729   2015-05-11   HR          Entry level         
5 5      peter    2843   2016-03-27   Finance     Senior Level        
6 6      lila     2413   2014-03-01   IT          Manager             
7 7      raj      5415   2015-07-23   Finance     Entry level         
8 8      tera     6413   2016-11-15   Operartions Senior Level

In [48]:
# Join (Merge) data frames (inner, outer, left, right) 
df1 = data.frame(CustomerId = c(1:6), Product = c(rep("Oven", 3), rep("Television", 3)))
df1

CustomerId Product   
1 1          Oven      
2 2          Oven      
3 3          Oven      
4 4          Television
5 5          Television
6 6          Television

In [49]:
df2 = data.frame(CustomerId = c(2, 4, 6), State = c(rep("California", 2), rep("Texas", 1)))
df2

CustomerId State     
1 2          California
2 4          California
3 6          Texas

In [50]:
# Merging happens based on the common column name in both the data sets
# Inner Join
df<-merge(x=df1,y=df2,by="CustomerId")
df

CustomerId Product    State     
1 2          Oven       California
2 4          Television California
3 6          Television Texas

In [51]:
# Outer Join
df<-merge(x=df1,y=df2,by="CustomerId",all=TRUE)
df

CustomerId Product    State     
1 1          Oven       NA        
2 2          Oven       California
3 3          Oven       NA        
4 4          Television California
5 5          Television NA        
6 6          Television Texas

In [52]:
# Left outer join
df<-merge(x=df1,y=df2,by="CustomerId",all.x=TRUE)
df

CustomerId Product    State     
1 1          Oven       NA        
2 2          Oven       California
3 3          Oven       NA        
4 4          Television California
5 5          Television NA        
6 6          Television Texas

In [53]:
# Right outer join 
df<-merge(x=df1,y=df2,by="CustomerId",all.y=TRUE)
df

CustomerId Product    State     
1 2          Oven       California
2 4          Television California
3 6          Television Texas

In [54]:
# Cross join
df<-merge(x = df1, y = df2, by = NULL)
df

CustomerId.x Product    CustomerId.y State     
1  1            Oven       2            California
2  2            Oven       2            California
3  3            Oven       2            California
4  4            Television 2            California
5  5            Television 2            California
6  6            Television 2            California
7  1            Oven       4            California
8  2            Oven       4            California
9  3            Oven       4            California
10 4            Television 4            California
11 5            Television 4            California
12 6            Television 4            California
13 1            Oven       6            Texas     
14 2            Oven       6            Texas     
15 3            Oven       6            Texas     
16 4            Television 6            Texas     
17 5            Television 6            Texas     
18 6            Television 6            Texas

In [55]:
# apply 
# Returns a vector or array or list of values obtained by applying a function to margins of an array or matrix.
x <- matrix(rnorm(30), nrow=5, ncol=6)
x

[,1]       [,2]       [,3]       [,4]        [,5]        [,6]      
[1,] -0.1632593 -1.2857900 -1.2855603 -1.02950362  0.80981181 -2.5856709
[2,]  1.4376748  1.6021222  0.2380039 -0.19653177  0.24923142 -0.6795733
[3,] -1.5364953 -1.3557490 -0.6185171 -1.24453991 -0.02617717  1.4720634
[4,] -0.1311956  0.6094029 -0.8530838 -0.08314446 -1.38854329  0.9247657
[5,] -0.3286450 -0.2469997  0.1762401  1.65691975 -0.65746465 -0.2518602

In [56]:
apply(x, 1 ,sum)

[1] -5.5399724  2.6509272 -3.3094151 -0.9217986  0.3481904

In [57]:
apply(x, 2 ,sum)

[1] -0.7219204 -0.6770136 -2.3429172 -0.8968000 -1.0131419 -1.1202754

In [58]:
apply(x, 1:2, function(x) x/2)

[,1]        [,2]       [,3]        [,4]        [,5]        [,6]      
[1,] -0.08162965 -0.6428950 -0.64278015 -0.51475181  0.40490590 -1.2928355
[2,]  0.71883739  0.8010611  0.11900194 -0.09826588  0.12461571 -0.3397866
[3,] -0.76824766 -0.6778745 -0.30925854 -0.62226995 -0.01308859  0.7360317
[4,] -0.06559778  0.3047014 -0.42654192 -0.04157223 -0.69427165  0.4623828
[5,] -0.16432248 -0.1234998  0.08812007  0.82845987 -0.32873233 -0.1259301

In [59]:
# lapply 
# lapply function takes list, vector or Data frame  as input and returns only list as output
A <- matrix(1:9, 3,3)
A
B <- matrix(4:15, 4,3)
B
C <- matrix(8:10, 3,2)
C

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[,1] [,2] [,3]
[1,] 4     8   12  
[2,] 5     9   13  
[3,] 6    10   14  
[4,] 7    11   15

[,1] [,2]
[1,]  8    8  
[2,]  9    9  
[3,] 10   10

In [60]:
MyList <- list(A,B,C)
MyList

[[1]]
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

[[2]]
     [,1] [,2] [,3]
[1,]    4    8   12
[2,]    5    9   13
[3,]    6   10   14
[4,]    7   11   15

[[3]]
     [,1] [,2]
[1,]    8    8
[2,]    9    9
[3,]   10   10

In [61]:
class(MyList)

[1] "list"

In [62]:
lapply(MyList, mean)

[[1]]
[1] 5

[[2]]
[1] 9.5

[[3]]
[1] 9

In [63]:
# sapply 
# sapply function takes list, vector or Data frame  as input. It is similar to lapply function but returns only vector as output
sapply(MyList, mean)

[1] 5.0 9.5 9.0

In [64]:
random <- c("This","is","random","vector")
random
sapply(random, nchar)

[1] "This"   "is"     "random" "vector"

This     is random vector 
     4      2      6      6

In [65]:
# mapply
# mapply applies FUN to the first elements of each (.) argument, the second elements, the third elements, and so on.
mapply(sum, c(1,2,3), c(4,5,6), c(7,8,9))
mapply(sum, matrix1, matrix2)

[1] 12 15 18

[1]  3  7 11 15

In [66]:
# tapply
# tapply is used when you want to apply a function to subsets of a vector and the subsets are 
# defined by some other vector, usually a factor
attach(iris)
iris

Sepal.Length Sepal.Width Petal.Length Petal.Width Species  
1   5.1          3.5         1.4          0.2         setosa   
2   4.9          3.0         1.4          0.2         setosa   
3   4.7          3.2         1.3          0.2         setosa   
4   4.6          3.1         1.5          0.2         setosa   
5   5.0          3.6         1.4          0.2         setosa   
6   5.4          3.9         1.7          0.4         setosa   
7   4.6          3.4         1.4          0.3         setosa   
8   5.0          3.4         1.5          0.2         setosa   
9   4.4          2.9         1.4          0.2         setosa   
10  4.9          3.1         1.5          0.1         setosa   
11  5.4          3.7         1.5          0.2         setosa   
12  4.8          3.4         1.6          0.2         setosa   
13  4.8          3.0         1.4          0.1         setosa   
14  4.3          3.0         1.1          0.1         setosa   
15  5.8          4.0         1.2          0.2         setosa   
16  5.7          4.4         1.5          0.4         setosa   
17  5.4          3.9         1.3          0.4         setosa   
18  5.1          3.5         1.4          0.3         setosa   
19  5.7          3.8         1.7          0.3         setosa   
20  5.1          3.8         1.5          0.3         setosa   
21  5.4          3.4         1.7          0.2         setosa   
22  5.1          3.7         1.5          0.4         setosa   
23  4.6          3.6         1.0          0.2         setosa   
24  5.1          3.3         1.7          0.5         setosa   
25  4.8          3.4         1.9          0.2         setosa   
26  5.0          3.0         1.6          0.2         setosa   
27  5.0          3.4         1.6          0.4         setosa   
28  5.2          3.5         1.5          0.2         setosa   
29  5.2          3.4         1.4          0.2         setosa   
30  4.7          3.2         1.6          0.2         setosa   
... ...          ...         ...          ...         ...      
121 6.9          3.2         5.7          2.3         virginica
122 5.6          2.8         4.9          2.0         virginica
123 7.7          2.8         6.7          2.0         virginica
124 6.3          2.7         4.9          1.8         virginica
125 6.7          3.3         5.7          2.1         virginica
126 7.2          3.2         6.0          1.8         virginica
127 6.2          2.8         4.8          1.8         virginica
128 6.1          3.0         4.9          1.8         virginica
129 6.4          2.8         5.6          2.1         virginica
130 7.2          3.0         5.8          1.6         virginica
131 7.4          2.8         6.1          1.9         virginica
132 7.9          3.8         6.4          2.0         virginica
133 6.4          2.8         5.6          2.2         virginica
134 6.3          2.8         5.1          1.5         virginica
135 6.1          2.6         5.6          1.4         virginica
136 7.7          3.0         6.1          2.3         virginica
137 6.3          3.4         5.6          2.4         virginica
138 6.4          3.1         5.5          1.8         virginica
139 6.0          3.0         4.8          1.8         virginica
140 6.9          3.1         5.4          2.1         virginica
141 6.7          3.1         5.6          2.4         virginica
142 6.9          3.1         5.1          2.3         virginica
143 5.8          2.7         5.1          1.9         virginica
144 6.8          3.2         5.9          2.3         virginica
145 6.7          3.3         5.7          2.5         virginica
146 6.7          3.0         5.2          2.3         virginica
147 6.3          2.5         5.0          1.9         virginica
148 6.5          3.0         5.2          2.0         virginica
149 6.2          3.4         5.4          2.3         virginica
150 5.9          3.0         5.1          1.8         virginica

In [67]:
tapply(iris$Sepal.Length, Species, mean) # mean of Sepal.Length for all 3 Species 

setosa versicolor  virginica 
     5.006      5.936      6.588

In [68]:
tapply(iris$Sepal.Width, Species, median)

setosa versicolor  virginica 
       3.4        2.8        3.0

In [69]:
# rapply
# rapply function in R is nothing but recursive apply, as the name suggests it is used to apply a 
# function to all elements of a list recursively
x=list(3,list(4,5),6,list(7,list(8,9)))
x

[[1]]
[1] 3

[[2]]
[[2]][[1]]
[1] 4

[[2]][[2]]
[1] 5


[[3]]
[1] 6

[[4]]
[[4]][[1]]
[1] 7

[[4]][[2]]
[[4]][[2]][[1]]
[1] 8

[[4]][[2]][[2]]
[1] 9

In [70]:
rapply(x,function(x) x^2,class=c("numeric"))

[1]  9 16 25 36 49 64 81

In [71]:
# vapply 
# vapply function in R is similar to sapply, but has a pre-specified type of return value, 
# so it can be safer (and sometimes faster) to use
vapply(1:5, sqrt, 1i)

[1] 1.000000+0i 1.414214+0i 1.732051+0i 2.000000+0i 2.236068+0i

In [72]:
# cat function
cat('one',2,'three',4,'five')
cat(1:10,sep="\t")
cat(1:10,sep="\n")
cat(1:10,file="num_series.xlsx",sep="\n",append ="FALSE") # By deafult is FALSE

one 2 three 4 five1	2	3	4	5	6	7	8	9	101
2
3
4
5
6
7
8
9
10


In [73]:
getwd() # to know the working directory 

[1] "C:/Users/Acer"

In [ ]:
setwd("E:\\Raj\\Training\\Data\\R Programmming") # to set the working directory 

In [74]:
set.seed(123) # reproducing same results
y <- matrix(rnorm(30), nrow=5, ncol=6)
y

[,1]        [,2]       [,3]       [,4]       [,5]       [,6]      
[1,] -0.56047565  1.7150650  1.2240818  1.7869131 -1.0678237 -1.6866933
[2,] -0.23017749  0.4609162  0.3598138  0.4978505 -0.2179749  0.8377870
[3,]  1.55870831 -1.2650612  0.4007715 -1.9666172 -1.0260044  0.1533731
[4,]  0.07050839 -0.6868529  0.1106827  0.7013559 -0.7288912 -1.1381369
[5,]  0.12928774 -0.4456620 -0.5558411 -0.4727914 -0.6250393  1.2538149

In [75]:
apply(y, 1 ,sum)

[1]  1.4110673  1.7082152 -2.1448300 -1.6713340 -0.7162311

In [76]:
apply(y, 2 ,sum)

[1]  0.9678513 -0.2215949  1.5395087  0.5467110 -3.6657336 -0.5798552

In [77]:
apply(y, 1:2, function(x) x/2)

[,1]        [,2]       [,3]        [,4]       [,5]       [,6]       
[1,] -0.28023782  0.8575325  0.61204090  0.8934566 -0.5339119 -0.84334666
[2,] -0.11508874  0.2304581  0.17990691  0.2489252 -0.1089875  0.41889352
[3,]  0.77935416 -0.6325306  0.20038573 -0.9833086 -0.5130022  0.07668656
[4,]  0.03525420 -0.3434264  0.05534136  0.3506780 -0.3644456 -0.56906847
[5,]  0.06464387 -0.2228310 -0.27792057 -0.2363957 -0.3125196  0.62690746

In [78]:
# R cat function with append="TRUE"
cat(1:10,file="num_series.csv",sep="\n")
cat(11:20,file="num_series.csv",sep="\n",append ="TRUE")